### ISSUE TITLE
Add option to word wrap or not

### ISSUE THREAD

**Issue by paul-bjorkstrand** [prftryan/LogTailerPlus#1]
While fitting the whole log line on the screen is nice, sometimes it is easier to read when the lines just spill over and overflow-x (e.g. when reading stacktraces).

An optional button/toggle to switch between wrap and overflow mode would help this use case

**Comment by prftryan** [comment]
Good idea - should be pretty easy to implement, will work on this.

**Comment by prftryan** [comment]
Added functionality on 06/06
