### ISSUE TITLE
Scroll to bottom of logs when view is updated

### ISSUE THREAD

**Issue by sbmvenancio** [prftryan/LogTailerPlus#3]
Would be useful to Scroll to bottom of logs when view is updated similar to what happens when youuse tail -f.

**Comment by prftryan** [comment]
This feature already exists, see the pin/tail toggle in the top right of each panel.  If it is not scrolling to the bottom still, might be a timing issue - please provide more details on browser/system if that is the case.

**Comment by prftryan** [comment]
This should be resolved with the latest "1.0.3" release.  Please re-open if you are still seeing issues.
